name: "appointment_bot"

services:
      bot:
        image: "appbot:latest"
        restart: "unless-stopped"
        environment:
        env_file: ".env"
        depends_on:
            - nats
            - postgres
            - redis
  nats:
    image: nats:latest
    entrypoint: /nats-server
    command: "-c /config/server.conf"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats/data:/data
      - ./nats/config/server.conf:/config/server.conf

  nats-nui:
    image: ghcr.io/nats-nui/nui:latest
    container_name: nats-nui
    ports:
      - "31311:31311"
    volumes:
      - ./nui/db:/db
    depends_on:
      - nats

  postgres:
    image: postgres:15-alpine
    restart: "always"
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: data
    volumes:
      - "appointment_bot:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: "always"
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - "appointment_bot:/var/lib/pgadmin"
    depends_on:
      - postgres

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    restart: on-failure
    volumes:
      - "./appointment_bot:/var/lib/redis/data"

volumes:
  appointment_bot-pgadmin:
  appointment_bot-postgres:
