name: "appointment_bot"

services:
  nats:
    image: nats:latest
    entrypoint: /nats-server
    command: "-c /config/server.conf"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats/data:/data
      - ./nats/config/server.conf:/config/server.conf
      -
  nats-nui:
    image: ghcr.io/nats-nui/nui:latest
    container_name: nats-nui
    ports:
      - "31311:31311"
    volumes:
      - ./nui/db:/db
    depends_on:
      - nats
      -

  postgres:
    image: postgres:15-alpine
    restart: "always"
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superpassword
      POSTGRES_DB: data
    volumes:
      - "01-simple-alchemy-postgres:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: "always"
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - "01-simple-alchemy-pgadmin:/var/lib/pgadmin"
    depends_on:
      - postgres

volumes:
  01-simple-alchemy-pgadmin:
  01-simple-alchemy-postgres:

  redis:
    image: redis:latest
    command:
      - redis-server
    restart: on-failure
    volumes:
      - "./schedule-app_bot-data-redis:/var/lib/redis/data"