"""Comment slots and user

Revision ID: 2f2937f5b131
Revises: 41d195c0e300
Create Date: 2024-12-21 18:50:13.130441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f2937f5b131'
down_revision: Union[str, None] = '41d195c0e300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slots', sa.Column('comment', sa.String(), nullable=True))
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('slots', 'comment')
    # ### end Alembic commands ###
