"""First migration

Revision ID: 92c8ddbed87e
Revises: 
Create Date: 2025-01-11 01:53:13.199159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c8ddbed87e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pcodes',
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('pcode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pcodes')
    # ### end Alembic commands ###
